config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.is_admin? } do
    resources :inspirations, path: '/admin/inspirations'
    resources :payments, path: '/admin/payments'
    get 'admin/users' => 'admin#users', as: 'admin_users'
    get 'admin/stats' => 'admin#stats', as: 'admin_stats'
    get 'admin/photos' => 'admin#photos', as: 'admin_photos'
  end

  devise_for :users, controllers: { registrations: 'registrations', session: 'sessions', passwords: 'passwords' }

  devise_scope :user do
    get 'settings/(:user_key)'     => 'registrations#settings', as: 'settings'
    match 'unsubscribe/:user_key'  => 'registrations#unsubscribe', as: 'unsubscribe', via: [:put]
  end

  get 'entries/import/(:type)'   => 'import#show', as: 'import'
  match 'entries/import/(:type)' => 'import#update', via: [:put], as: 'import_process'
  match '/entries/import/ohlife/upload'  => 'import#process_ohlife_images', via: [:post], :as => 'import_ohlife_images'
  get 'entries/export'   => 'entries#export', as: 'export_entries'
  get 'entries/calendar' => 'entries#calendar', as: 'entries_calendar'

  get 'past(/:anything)',               to: redirect('/entries')
  get 'entries/random',                 to: 'entries#random', as: 'random_entry'
  get 'entries/:year/:month/:day',      to: 'entries#show',  as: 'day_entry'
  resources :entries, except: [:show]
  get 'entries/(:group)(/:subgroup)',   to: 'entries#index',  as: 'group_entries'  
  get 'latest',                         to: 'entries#latest', as: 'latest_entry'
  get 'review/(:year)',                 to: 'entries#review', as: 'review'
  get 'play',                           to: 'entries#spotify', as: 'spotify'
  get 'search',                         to: 'searches#show'
  get 'write',                          to: redirect('/entries/new')
  get 'privacy',                        to: 'welcome#privacy'
  get 'terms',                          to: 'welcome#terms'
  get 'features',                       to: 'welcome#features'
  get 'faqs',                           to: 'welcome#faqs'
  get 'subscribe',                      to: 'welcome#subscribe'
  get 'donate',                         to: redirect('/subscribe')
  get 'pro',                            to: redirect('/subscribe')
  match 'payment_notify',               to: 'payments#payment_notify', via: [:post]
  get 'ohlife-alternative',             to: 'welcome#ohlife_alternative'
  post 'email_processor',               to: 'griddler/emails#create'
  post 'email_events',                  to: 'email_events#create'

  root 'welcome#index'  

  get "*any", via: :all, to: "errors#not_found"
end

app/controllers/entries_controller.rb
# Handle Web Entries
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, :require_entry_permission, only: [:show, :edit, :update, :destroy]

  def index
    if params[:group] == 'photos'
      @entries = current_user.entries.includes(:inspiration).only_images
      @title = 'Photo Entries'
    elsif params[:subgroup].present?
      from_date = "#{params[:group]}-#{params[:subgroup]}"
      to_date = "#{params[:group]}-#{params[:subgroup].to_i + 1}"
      @entries = current_user.entries.includes(:inspiration).where("date >= to_date('#{from_date}','YYYY-MM') AND date < to_date('#{to_date}','YYYY-MM')").sort_by(&:date)
      date = Date.parse(params[:subgroup] + '/' + params[:group])
      @title = "Entries from #{date.strftime('%b %Y')}"
    elsif params[:group].present?
      begin
        raise 'not a year' unless params[:group] =~ /(19|20)[0-9]{2}/
        @entries = current_user.entries.includes(:inspiration).where("date >= '#{params[:group]}-01-01'::DATE AND date <= '#{params[:group]}-12-31'::DATE").sort_by(&:date)
      rescue
        Rails.logger.warn("Doing expensive lookup based on ID for entry #{params[:group]} by #{current_user.email}")
        entry = current_user.entries.find(params[:group])
        return redirect_to day_entry_path(year: entry.date.year, month: entry.date.month, day: entry.date.day)
      end
      @title = "Entries from #{params[:group]}"
    elsif params[:format] != "json"
      @entries = current_user.entries.includes(:inspiration)
      @title = 'All Entries'
    end

    if @entries.present?
      @entries = Kaminari.paginate_array(@entries).page(params[:page]).per(params[:per])
    elsif params[:format] != "json"
      redirect_to latest_entry_path and return
    end

    respond_to do |format|
      format.json {
        render json: calendar_json(current_user.entries
          .where("date >= '#{params[:start]}'::DATE AND date < '#{params[:end]}'::DATE")) }
      format.html
    end
  end

  def show
    if @entry
      track_ga_event('Show')
      render 'show'
    else
      redirect_to entries_path
    end
  end

  def latest
    @lastest_entry = current_user.entries.includes(:inspiration).sort_by(&:date).last
  end

  def random
    @entry = current_user.random_entry
    if @entry
      track_ga_event('Random')
      render 'show'
    else
      redirect_to entries_path
    end
  end

  def new
    @entry = Entry.new
    @random_inspiration = random_inspiration
  end

  def calendar
  end

  def spotify
  end

  def create
    if current_user.is_free?
      flash[:alert] = "<a href='#{subscribe_url}'' class='alert-link'>Subscribe to PRO</a> to write new entries.".html_safe
      redirect_to root_path and return
    end

    @existing_entry = current_user.existing_entry(params[:entry][:date].to_s)

    if @existing_entry.present? && params[:entry][:entry].present?
      @existing_entry.body += "<hr>#{params[:entry][:entry]}"
      @existing_entry.inspiration_id = params[:entry][:inspiration_id] if params[:entry][:inspiration_id].present?
      if @existing_entry.image_url_cdn.blank? && params[:entry][:image].present?
        @existing_entry.image = params[:entry][:image]
      end
      if @existing_entry.save
        flash[:notice] = "Merged with existing entry on #{@existing_entry.date.strftime("%B %-d")}."
        track_ga_event('Merged')
        redirect_to day_entry_path(year: @existing_entry.date.year, month: @existing_entry.date.month, day: @existing_entry.date.day)
      else
        render 'new'
      end
    else
      @entry = current_user.entries.create(entry_params)
      if @entry.save
        track_ga_event('New')
        flash[:notice] = "Entry created successfully!"
        redirect_to day_entry_path(year: @entry.date.year, month: @entry.date.month, day: @entry.date.day)
      else
        render 'new'
      end
    end
  end

  def edit
    store_location
    if current_user.is_free?
      @entry.body = @entry.sanitized_body
    end
    track_ga_event('Edit')
  end

  def update
    if current_user.is_free?
      flash[:alert] = "<a href='#{subscribe_url}'' class='alert-link'>Subscribe to PRO</a> to edit entries.".html_safe
      redirect_to root_path and return
    end

    @existing_entry = current_user.existing_entry(params[:entry][:date].to_s)

    if @entry.present? && @existing_entry.present? && @entry != @existing_entry && params[:entry][:entry].present?
      # existing entry exists, so add to it
      @existing_entry.body += "<hr>#{params[:entry][:entry]}"
      @existing_entry.inspiration_id = params[:entry][:inspiration_id] if params[:entry][:inspiration_id].present?
      if @existing_entry.image_url_cdn.blank? && @entry.image.present?
        @existing_entry.image = @entry.image
      elsif @entry.image.present?
        @existing_entry.body += "<br><a href='#{@entry.image_url_cdn}'><img src='#{@entry.image_url_cdn}'></a>"
      end
      if @existing_entry.save
        @entry.delete
        flash[:notice] = "Merged with existing entry on #{@existing_entry.date.strftime('%B %-d')}."
        track_ga_event('Update')
        redirect_to day_entry_path(year: @existing_entry.date.year, month: @existing_entry.date.month, day: @existing_entry.date.day) and return
      else
        render 'edit'
      end
    elsif params[:entry][:entry].blank?
      @entry.destroy
      flash[:notice] = 'Entry deleted!'
      redirect_back_or_to entries_path
    else
      if @entry.image_url_cdn.present? && entry_params[:remove_image] == "0"
        @entry.remote_image_url = @entry.image_url_cdn
        update_params = entry_params.permit(:entry, :date)
      else
        update_params = entry_params.permit(:entry, :date, :image, :remove_image)
      end
      if @entry.update(entry_params)
        track_ga_event('Update')
        flash[:notice] = "Entry successfully updated!"
        redirect_to day_entry_path(year: @entry.date.year, month: @entry.date.month, day: @entry.date.day)
      else
        render 'edit'
      end
    end
  end

  def destroy
    if current_user.is_free?
      flash[:alert] = "<a href='#{subscribe_url}'' class='alert-link'>Subscribe to PRO</a> to edit entries.".html_safe
      redirect_to root_path and return
    end

    @entry.destroy
    track_ga_event('Delete')
    flash[:notice] = 'Entry deleted successfully.'
    redirect_to entries_path
  end

  def export
    if params[:only_images] == "true"
      @entries = current_user.entries.only_images.sort_by(&:date)
    else
      @entries = current_user.entries.sort_by(&:date)
    end
    track_ga_event('Export')
    respond_to do |format|
      format.json { send_data JSON.pretty_generate(JSON.parse(@entries.to_json(only: [:date, :body, :image]))), filename: "export_#{Time.now.strftime('%Y-%m-%d')}.json" }
      format.txt do
        response.headers['Content-Type'] = 'text/txt'
        response.headers['Content-Disposition'] = "attachment; filename=export_#{Time.now.strftime('%Y-%m-%d')}.txt"
        render 'text_export'
      end
    end
  end

  def review
    month = Date.today.month
    @year = params[:year] || (month > 11 ? Time.now.year : Time.now.year - 1)
    @entries = current_user.entries.where("date >= '#{@year}-01-01'::DATE AND date <= '#{@year}-12-31'::DATE")
    @total_count = @entries.count
    if @total_count > 0
      @body_text = @entries.map { |e| ActionView::Base.full_sanitizer.sanitize(e.body) }.join(" ")
      @words_counter = WordsCounted.count(@body_text, exclude: Entry::WORDS_NOT_TO_COUNT)
      if @total_count > 20
        all_user_entry_count = Entry.where("date >= '#{@year}-01-01'::DATE AND date <= '#{@year}-12-31'::DATE").group(:user_id).reorder("count_all").count.values
        @pctile = (((all_user_entry_count.find_index(@total_count) + 1).to_f / (all_user_entry_count.count)) * 100).round
      end
    else
      flash[:notice] = "No entries in #{@year} - nothing to review :("
      redirect_to entries_path
    end
  end

  private

  def track_ga_event(action)
    if ENV['GOOGLE_ANALYTICS_ID'].present?
      tracker = Staccato.tracker(ENV['GOOGLE_ANALYTICS_ID'])
      tracker.event(category: 'Web Entry', action: action, label: current_user.user_key)
    end
  end

  def entry_params
    params.require(:entry).permit(:date, :entry, :image, :inspiration_id, :remove_image, :remote_image_url)
  end

  def set_entry
    if params[:day].present?
      date = Date.parse("#{params[:year]}-#{params[:month]}-#{params[:day]}")
      @entry = current_user.entries.includes(:inspiration).where(date: date).first
    else
      @entry = current_user.entries.includes(:inspiration).where(id: params[:id]).first
    end
  end

  def require_entry_permission
    return false if @entry.present? && current_user == @entry.user
    flash[:alert] = 'Not authorized'
    redirect_to entries_path
  end

  def random_inspiration
    count = Inspiration.without_imports_or_email.count
    return nil if count == 0
    Inspiration.without_imports_or_email.offset(rand(count)).first
  end

  def calendar_json(entries)
    return false unless current_user.is_pro?
    json_hash = []
    entries.each do |entry|
      if entry.image.present?
        title = "📸#{ActionController::Base.helpers.strip_tags(entry.sanitized_body.gsub(/\n/, '')).truncate(40, separator: ' ')}"
      else
        title = ActionController::Base.helpers.strip_tags(entry.sanitized_body.gsub(/\n/, '')).truncate(50, separator: ' ')
      end
      json_hash <<  {
        id: entry.id,
        title: title,
        url: day_entry_path(year: entry.date.year, month: entry.date.month, day: entry.date.day),
        start: entry.date.strftime('%Y-%m-%d'),
        allDay: 'true'
      }
    end
    json_hash.to_json
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def image_code(entry)
    converted_image_url = entry.image_url_cdn
    image_tag converted_image_url, data: { src: converted_image_url }, alt: "#{entry.date_format_short}"
  end

  def format_body(body)
    body = Rinku.auto_link(body, :all, 'target="_blank"')
    sanitize body, tags: %w(strong em a div span ul ol li b i img br p hr), attributes: %w(href style src target)
  end
end

app/views/entries/_entry.html.haml
.center
  - if entry.exactly_past_years(current_user)
    - year_back = Time.now.in_time_zone(current_user.send_timezone).year - entry.date.year
    .label.label-past-years #{pluralize(year_back,"year").upcase} AGO
  .s-entry-date
    -if entry.inspiration.present?
      .float-left.s-edit-entry{rel: "popover", title: "#{entry.inspiration.inspired_by}", data: { content: "#{entry.inspiration.body.html_safe}" } }
        %i.fa.fa-lightbulb-o
    .float-right.s-edit-entry
      = link_to edit_entry_path(entry), rel: "tooltip", title: "Edit Entry" do
        %i.fa.fa-pencil-square-o
    %h2
      = link_to entry.date_format_short, day_entry_path(year: entry.date.year, month: entry.date.month, day: entry.date.day)
    %h3
      %span
        = entry.date_day.upcase
.s-scrollable
  - if @search.present?
    = highlight(format_body(entry.body), @search.term)
  - else
    = format_body(entry.body)
  = entry.spotify_embed
  - if (hashtags = entry.hashtags).present?
    %p.tags
      %strong.small Tags: 
      - hashtags.each do |tag|
        - if (date = current_user.hashtags.select{|h| h.tag&.downcase == tag.downcase}.first&.date).present?
          = link_to search_url(host: ENV['MAIN_DOMAIN'], search: {term: "##{tag}"}), class: "noline", rel: "tooltip-mobile-friendly", title: "#{tag_relative_date(date, entry.date)}" do
            %span.label.label-primary= tag
        - else
          = link_to search_url(host: ENV['MAIN_DOMAIN'], search: {term: "##{tag}"}), class: "noline" do
            %span.label.label-primary= tag
- if entry.image_url_cdn.present?
  .pictureFrame
    =link_to entry.image_url_cdn, target: "_blank" do
      =image_code(entry)
.clearfix

:javascript
  $("#entry-#{entry.id}").imagesLoaded()
    .done( function( instance ) {
      $(instance.elements).find('.pictureFrame img').css("background-image","none");
    });

app/views/entries/calendar.html.haml
- title "Calendar View"
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.3/fullcalendar.min.js"
= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.3/fullcalendar.min.css"

- if current_user.is_free?
  .alert.alert-warning
    =link_to "Subscribe to PRO", subscribe_path, class: "alert-link"
    to unlock the ability to see your existing entries on the calendar.

#calendar

:css
  #calendar {
    margin-top:25px;
  }
  .fc-widget-content {
    cursor:pointer;
  }

  #calendar .fc-button {
    outline: none;
  }

:javascript
  $(document).ready(function() {
      $('#calendar').fullCalendar({
        header: {
          right: 'prev,next today',
          center: '',
          left: 'title'
        },
        height: 450,
        selectable: true,
        selectHelper: true,
        select: function(start, end, allDay) {
          $(".navbar-brand i.fa-spinner").addClass("fa-spin");
          window.location.href = "#{new_entry_url}?day="+start.format('YYYY-MM-DD');
        },
        events: "#{entries_path(format:'json')}"
      })
  });

- if params[:day].present?
  :javascript
    $(document).ready(function() {
      $('#calendar').fullCalendar('gotoDate', "#{params[:day]}");
    });

app/views/entries/edit.html.haml
- title "Edit Entry on #{@entry.date_format_long}"
- add_class = 'blur' if current_user.is_free?

.row
  %br
  -if current_user.is_free?
    .col-md-8.col-md-offset-2
      .alert.alert-warning
        =link_to "Subscribe to PRO", subscribe_path, class: "alert-link"
        to unlock the ability to edit entries.

  .col-md-8.col-md-offset-2.well.s-new-edit-entry{id: "entry-#{@entry.id}"}
    %div{class: add_class}
      .s-entry-date.s-new-entry
        -if @entry.inspiration.present?
          .float-left.s-edit-entry{rel: "popover", title: "#{@entry.inspiration.inspired_by}", data: { content: "#{@entry.inspiration.body.html_safe}" }}
            %i.fa.fa-lightbulb-o
        .float-right.s-edit-entry{rel: "tooltip", title: "Delete this Entry"}
          = link_to entry_path(@entry), class: "s-delete", method: :delete, data: { confirm: 'Are you sure you want to delete this entry? There is no undo.' } do
            %i.fa.fa-trash
        %h2= @entry.date_format_short
        %h3
          %span
            = @entry.date_day.upcase

      = form_for :entry, url: entry_path(@entry), method: :patch do |f|

        -if @entry.errors.any?
          #error_explanation
            .alert.alert-danger
              - @entry.errors.full_messages.each do |msg|
                %p= msg

        %div
          = f.label :date
          .input-group.date
            %span.input-group-addon
              %i.fa.fa-calendar
            = f.text_field :date, value: @entry.date_format_short, placeholder: "October 11 2014", class: "form-control pickadate"
          %br

        %div

          - if @entry.image.present?
            %label
              = f.check_box :remove_image, class: 'j-image-remove'
              &nbsp;Remove Photo
            %br
            .pictureFrame.editable.j-image-preview
              =link_to @entry.image_url_cdn, target: "_blank" do
                =image_code(@entry)
          - else
            = f.label :image, "Photo"
            = f.file_field :image, accept: "image/png,image/gif,image/jpeg,image/heic"
          %br

        %div
          = f.label :entry
          = f.text_area :entry, class: "form-control summernote", rows: 15
          %br

        %div
          = f.submit "Update Entry", class: "form-control btn btn-primary"

:javascript
  var summer_note = $('#entry_entry');
  summer_note.summernote({
    mode: 'text/html',
    height: 300,
    theme: 'flatly',
    disableDragAndDrop: true,
    focus: true,
    toolbar: [["style", ["bold", "italic", "underline", "clear"]], ["layout", ["ul", "ol"]], ['insert', ['link']], ['misc', ['fullscreen', 'codeview']]]
  });

  summer_note.summernote("code", summer_note.val())
  summer_note.closest('form').submit(function() {
    summer_note.val(summer_note.summernote("code"));
    return true;
  });

  $("#entry-#{@entry.id}").imagesLoaded()
    .done( function( instance ) {
      $(instance.elements).find('.pictureFrame img').css("background-image","none");
    });

app/views/entries/index.html.haml
- title "#{@title} on Dabble Me"
.row
  .col-md-8.col-md-offset-1
    - if current_user.is_free?
      .alert.alert-info.hidden-xs
        =link_to subscribe_path,:class=>"float-left" do
          %button.btn.btn-success Subscribe Now
        %strong Dabble Me PRO
        for $3/mo unlocks changing frequency of emails, adding/editing entries via the web, adding a photo to entries, and plenty more.
      .clearfix

    %h3.visible-sm.visible-xs
      #{@title.upcase.html_safe}
      =link_to "javascript:void(0);", onclick: "$('.j-calendar').slideToggle('fast');", class: "s-toggle-calendar" do
        %i.fa.fa-calendar
  
  .col-xs-11.col-sm-5.col-md-2.s-date-groups.j-calendar
    %h3
      =link_to entries_path, class: "#{'active' if current_page?(entries_path)}" do
        .s-date-left
          ALL
        .s-date-right
          #{current_user.entries.length}
        .clearfix

    - if (only_images = current_user.entries.only_images.length) > 0
      %h4
        =link_to group_entries_path('photos'), class: "#{'active' if current_page?(group_entries_path('photos'))}" do
          .s-date-left
            PHOTOS
          .s-date-right
            #{only_images}
          .clearfix

    - current_user.entries.group_by{|c| c.date.strftime "%Y" }.each do |year_str,year_entries|
      %h4.s-date-year
        =link_to group_entries_path(year_str), class: "#{'active' if params[:group] == year_str}" do
          .s-date-left
            = year_str.upcase
          .s-date-right
            #{year_entries.length}
          .clearfix

      - year_entries.group_by{|c| c.date.strftime "%b" }.each do |month_str,date_entries|
        .s-date-left
          =link_to entries_calendar_path(day: year_str+"-"+month_str.to_date.strftime('%m')), class: "noline" do
            %i.fa.fa-calendar
          &nbsp;        
        =link_to group_entries_path(year_str, month_str.to_date.strftime('%m')), :class => "#{'active' if params[:group] == year_str && params[:subgroup] == month_str.to_date.strftime('%m')}" do
          .s-date-left
            = month_str.upcase
          .s-date-right
            #{date_entries.length}
          .clearfix

  .col-md-8.col-md-offset-1
    %br
    = form_for Search.new(), url: search_path, method: :get, html: { class: "form-horizontal" } do |f|
      .form-group
        .col-xs-8.col-sm-10
          = f.text_field :term, class: "form-control input-lg s-search-with-clear", autofocus: true, placeholder: "Search your entries..."
        .col-xs-4.col-sm-1
          = f.submit "Search", class: "btn btn-primary btn-lg"

  .col-md-8.col-md-offset-1
    .center
      = paginate @entries

  - @entries.each do |entry|
    .col-md-8.col-md-offset-1.well.entry{:id => "entry-#{entry.id}"}
      = render partial: 'entries/entry', locals: { entry: entry }

  .col-md-8.col-md-offset-1
    .center
      = paginate @entries

app/views/entries/review.html.haml
- title ("Year In Review")
= javascript_include_tag "//www.gstatic.com/charts/loader.js", "chartkick"
- add_class = 'really-blur' if current_user.is_free?
.row.s-year-in-review
  .col-md-8.col-md-offset-2
    %h3= "#{@year} Year In Review"
    - ((Date.today.year - 11)..Date.today.year).each do |year|
      - entries_for_year = current_user.entries.where("date >= '#{year}-01-01'::DATE AND date <= '#{year}-12-31'::DATE")
      - if entries_for_year.any?
        = link_to "#{year}", review_path(year), style: "margin: 0 5px; font-size: 16px;"
    .clearfix
    %br
    %br      

  .col-md-8.col-md-offset-2.well
    .center
      .s-entry-date
        %h2 Days with Entries
        %h3
          %span= "#{@total_count} entries in #{@year}"
      .s-review-details
        = pie_chart({"Days With Entries": @total_count, "Days Without Entires": (365 - @total_count)},  height: "230px", library: {backgroundColor: "#ffffff"})
        .clearfix
        - if @pctile.present?
          %p= "You're in the #{@pctile.ordinalize} percentile compared to all active Dabble Me users in #{@year}."
          .clearfix

  - if current_user.is_free?
    .col-md-8.col-md-offset-2
      .alert.alert-warning
        =link_to "Subscribe to PRO", subscribe_path, class: "alert-link"
        to see the rest of your Year in Review.

  .col-md-8.col-md-offset-2.well
    .center{class: add_class}
      .s-entry-date
        %h2 Days of Entries
        - days = @entries.pluck("to_char(date, 'Dy')")
        - counts = Hash.new(0)
        - days.each { |name| counts[name.strip] += 1 }
        %h3
          %span= "#{pluralize(counts.length, 'day')} a week"
      .s-review-details
        - sorted_counts = Hash.new
        - Date::ABBR_DAYNAMES.each_with_index { |x, i| sorted_counts[x] = counts[x] }
        = column_chart sorted_counts, discrete: true, library: { backgroundColor: "#ffffff" }
        .clearfix

  .col-md-8.col-md-offset-2.well
    .center{class: add_class}
      .s-entry-date
        %h2 Months of Entries
        - months = @entries.pluck("to_char(date, 'Mon')")
        - counts = Hash.new(0)
        - months.each { |name| counts[name.strip] += 1 }        
        %h3
          %span= "#{pluralize(counts.length, 'month')} covered"
      .s-review-details
        - sorted_counts = Hash.new
        - Date::ABBR_MONTHNAMES.reject(&:blank?).each_with_index { |x, i| sorted_counts[x] = counts[x] }
        = column_chart sorted_counts, discrete: true, library: { backgroundColor: "#ffffff" }
        .clearfix

  .col-md-8.col-md-offset-2.well
    .center{class: add_class}
      .s-entry-date
        %h2 Total Words
        %h3
          - percent_book = ((@words_counter.token_count.to_f/124000).to_f * 100).round
          - book_height = 500-((percent_book.to_f / 100) * 500)
          %span= "#{number_with_delimiter(@words_counter.token_count)} - #{percent_book}% of Caste".html_safe
      .s-review-details
        %div{style: 'position: relative;'}
          =link_to 'https://amzn.to/34JoS7j', target: '_blank', style: "margin-top: 20px; display: block;margin-bottom: 10px;" do
            .s-book-cover{style: "height: #{book_height < 0 ? 0 : book_height}px"}
            = image_tag 'caste.jpg', width: 329, height: 500
        .clearfix

  .col-md-8.col-md-offset-2.well
    .center{class: add_class}
      .s-entry-date
        %h2 Average Words per Post
        %h3
          - your_avg_words = @words_counter.token_count / @total_count
          %span= number_with_delimiter(your_avg_words)
      - if @year.to_s == "2020"
        .s-review-details
          - if your_avg_words > 298
            - compared = 'way more'
          - elsif your_avg_words > 199
            - compared = 'more'
          - elsif your_avg_words < 99
            - compared = 'way less'
          - else
            - compared = 'less'
          %p= "That's #{compared} than the average of all Dabble Me users (116 words per post)."
          %p
            %span Collectively, all Dabble Me users could have wrote 37 novels equivalent to Isabel Wilkerson's,
            %span<= link_to "Caste: The Origins of Our Discontents", "https://amzn.to/361quIf", target: :_blank
            %span !
          .clearfix  

  .col-md-8.col-md-offset-2.well
    .center{class: add_class}
      .s-entry-date
        %h2 Average Characters per Post
        %h3
          - avg_chars = @body_text.length / @total_count
          - tweets = ((avg_chars).to_f / 280).ceil
          - your_avg_words = @words_counter.token_count / @total_count
          %span= "#{number_with_delimiter(avg_chars)} - about #{tweets} tweets"
      .s-review-details
        .s-twitter-comparison
          - (1..tweets).each do |i|
            %i.fa.fa-twitter
        .clearfix


  - hashtags = Hash[*current_user.used_hashtags(@entries, false).inject(Hash.new(0)) { |h,v| h[v] += 1; h }.sort_by{|k,v| v}.reverse.flatten]
  - if hashtags.present?
    .col-md-8.col-md-offset-2.well
      .center{class: add_class}
        .s-entry-date
          %h2 Most Frequent Hashtags
        .s-review-details
          - hashtags.first(25).each do |k, v|
            %h3
              = link_to k, search_url(host: ENV['MAIN_DOMAIN'], search: {term: "##{k}"}), class: "noline"
              %span.middot= "&middot; #{v}".html_safe
          .clearfix

  .col-md-8.col-md-offset-2.well
    .center{class: add_class}
      .s-entry-date
        %h2 Most Frequent Words
        - if @year.to_s == "2020"
          %h3
            %span= "We're all still journaling in first-person...we collectively used <i>\"I\"</i> 160,271 times in our entries!".html_safe
      .s-review-details
        - @words_counter.token_frequency.first(25).each do |word|
          %h3
            =word.first
            %span.middot= "&middot; #{word.second}".html_safe
        .clearfix