config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.is_admin? } do
    resources :inspirations, path: '/admin/inspirations'
    resources :payments, path: '/admin/payments'
    get 'admin/users' => 'admin#users', as: 'admin_users'
    get 'admin/stats' => 'admin#stats', as: 'admin_stats'
    get 'admin/photos' => 'admin#photos', as: 'admin_photos'
  end

  devise_for :users, controllers: { registrations: 'registrations', session: 'sessions', passwords: 'passwords' }

  devise_scope :user do
    get 'settings/(:user_key)'     => 'registrations#settings', as: 'settings'
    match 'unsubscribe/:user_key'  => 'registrations#unsubscribe', as: 'unsubscribe', via: [:put]
  end

  get 'entries/import/(:type)'   => 'import#show', as: 'import'
  match 'entries/import/(:type)' => 'import#update', via: [:put], as: 'import_process'
  match '/entries/import/ohlife/upload'  => 'import#process_ohlife_images', via: [:post], :as => 'import_ohlife_images'
  get 'entries/export'   => 'entries#export', as: 'export_entries'
  get 'entries/calendar' => 'entries#calendar', as: 'entries_calendar'

  get 'past(/:anything)',               to: redirect('/entries')
  get 'entries/random',                 to: 'entries#random', as: 'random_entry'
  get 'entries/:year/:month/:day',      to: 'entries#show',  as: 'day_entry'
  resources :entries, except: [:show]
  get 'entries/(:group)(/:subgroup)',   to: 'entries#index',  as: 'group_entries'  
  get 'latest',                         to: 'entries#latest', as: 'latest_entry'
  get 'review/(:year)',                 to: 'entries#review', as: 'review'
  get 'play',                           to: 'entries#spotify', as: 'spotify'
  get 'search',                         to: 'searches#show'
  get 'write',                          to: redirect('/entries/new')
  get 'privacy',                        to: 'welcome#privacy'
  get 'terms',                          to: 'welcome#terms'
  get 'features',                       to: 'welcome#features'
  get 'faqs',                           to: 'welcome#faqs'
  get 'subscribe',                      to: 'welcome#subscribe'
  get 'donate',                         to: redirect('/subscribe')
  get 'pro',                            to: redirect('/subscribe')
  match 'payment_notify',               to: 'payments#payment_notify', via: [:post]
  get 'ohlife-alternative',             to: 'welcome#ohlife_alternative'
  post 'email_processor',               to: 'griddler/emails#create'
  post 'email_events',                  to: 'email_events#create'

  root 'welcome#index'  

  get "*any", via: :all, to: "errors#not_found"
end

app/views/shared/_favicons_and_metatags.html.haml
-#GENERATED FROM http://realfavicongenerator.net/
%link{href: "/apple-touch-icon-precomposed.png", rel: "apple-touch-icon-precomposed apple-touch-icon"}
%link{href: "/apple-touch-icon-57x57.png", rel: "apple-touch-icon", sizes: "57x57"}
%link{href: "/apple-touch-icon-114x114.png", rel: "apple-touch-icon", sizes: "114x114"}
%link{href: "/apple-touch-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72"}
%link{href: "/apple-touch-icon-144x144.png", rel: "apple-touch-icon", sizes: "144x144"}
%link{href: "/apple-touch-icon-60x60.png", rel: "apple-touch-icon", sizes: "60x60"}
%link{href: "/apple-touch-icon-120x120.png", rel: "apple-touch-icon", sizes: "120x120"}
%link{href: "/apple-touch-icon-76x76.png", rel: "apple-touch-icon", sizes: "76x76"}
%link{href: "/apple-touch-icon-152x152.png", rel: "apple-touch-icon", sizes: "152x152"}
%link{href: "/apple-touch-icon-180x180.png", rel: "apple-touch-icon", sizes: "180x180"}
%meta{content: "Dabble Me", name: "apple-mobile-web-app-title"}
%link{href: "/favicon-192x192.png", rel: "icon", sizes: "192x192", type: "image/png"}
%link{href: "/favicon-160x160.png", rel: "icon", sizes: "160x160", type: "image/png"}
%link{href: "/favicon-96x96.png", rel: "icon", sizes: "96x96", type: "image/png"}
%link{href: "/favicon-16x16.png", rel: "icon", sizes: "16x16", type: "image/png"}
%link{href: "/favicon-32x32.png", rel: "icon", sizes: "32x32", type: "image/png"}
%meta{content: "#9f00a7", name: "msapplication-TileColor"}
%meta{content: "/mstile-144x144.png", name: "msapplication-TileImage"}
%meta{content: "Dabble Me", name: "application-name"}
%meta{content: "Your own private place to write. A journal/diary to help you remember what's happened in your life.", property: "description"}
%meta{content: "dabble me,journal,diary,journaling,online diary,baby journal", property: "keywords"}
%link{href: "Dabble Me", rel: "author"}
%meta{content: "summary_large_image", name: "twitter:card"}
%meta{content: "@parterburn", name: "twitter:site"}
%meta{content: "Dabble Me - a private place to write", name: "twitter:title"}
%meta{content: "Your own private place to write. A journal/diary to help you remember what's happened in your life.", name: "twitter:description"}
%meta{content: "http://dabble.me/dabble_logo_ogimage.png", name: "twitter:image:src"}
%meta{content: "dabble.me", name: "twitter:domain"}
%meta{content: "Dabble Me - a private place to write", property: "og:title"}
%meta{content: "Your own private place to write. A journal/diary to help you remember what's happened in your life.", property: "og:description"}
%meta{content: "http://dabble.me/dabble_logo_ogimage.png", property: "og:image"}
%meta{content: "https://dabble.me/dabble_logo_ogimage.png", property: "og:image:secure_url"}

app/views/shared/_footer.html.haml
%footer.footer
  .container
    %hr
    .row
      .col-sm-5
        %p.muted.float-left
          =link_to "CONTACT & FAQS", faqs_path, title: "Contact & FAQs"
          &nbsp;&middot;&nbsp;
          = link_to "PRIVACY", privacy_path, title: "Privacy Policy"
          &nbsp;&middot;&nbsp;
          = link_to "TERMS", terms_path, title: "Terms of Service"
          -if current_user && current_user.is_free?
            &nbsp;&middot;&nbsp;
            =link_to "SUBSCRIBE TO PRO", subscribe_path, title: "Subscribe Now"
      .col-sm-2
        - if (ENV["SQREEN_TOKEN"].present? && !signed_in?)
          .text-center{style: "margin: 0 auto 10px auto;"}
            = link_to "https://www.sqreen.io/?utm_source=badge", title: "Realtime application protection", target: :_blank do
              = image_tag "https://s3-eu-west-1.amazonaws.com/sqreen-assets/badges/20171107/sqreen-light-badge.svg", style: "width:109px;height:36px", alt: "Sqreen | Runtime Application Protection", class: "sqreen-logo"      
      .col-sm-5
        %p.muted.float-right
          &nbsp;&nbsp;
          = link_to 'https://paularterburn.com/', title: "Made by Paul Arterburn" do
            © #{Time.now.year} Dabble Dev LLC


.j-back-to-top.s-back-to-top
  =link_to "#" do
    %span.fa-stack.fa-sm
      %i.fa.fa-square.fa-stack-2x
      %i.fa.fa-arrow-up.fa-stack-1x.fa-inverse

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
  .container
    .navbar-header
      %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '.navbar-collapse' } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if user_signed_in? && current_user.is_pro?
        =link_to new_entry_path, class: "s-write-icon visible-xs #{'active' if params[:controller] == 'entries' && params[:action].in?(['new', 'create'])}" do
          %i.fa.fa-pencil
      = link_to root_path, class: 'navbar-brand', title: "Dabble Me" do
        %span
          DABBLE ME

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if !user_signed_in?
          %li{class: "#{'active' if current_page?(features_path)}"}
            =link_to features_path do
              %span FEATURES
          %li{class: "#{'active' if current_page?(subscribe_path)}"}
            =link_to subscribe_path do
              %span PRICING
        - else
          %li{class: "#{'active' if params[:controller] == 'entries' && params[:action] == 'index'}"}
            =link_to entries_path do
              %span ENTRIES

          %li{class: "#{'active' if params[:controller] == 'entries' && params[:action].in?(['new', 'create'])}"}
            =link_to new_entry_path do
              %span WRITE

          %li{class: "#{'active' if current_page?(random_entry_path)}"}
            =link_to random_entry_path, title: "Random Entry" do
              %i.fa.fa-random.hidden-xs
              %span.visible-xs-inline-block RANDOM

          %li{class: "#{'active' if current_page?(random_entry_path)}"}
            =link_to spotify_path, title: "Songs from Entries" do
              %i.fa.fa-music.hidden-xs
              %span.visible-xs-inline-block SONGS

          %li{class: "#{'active' if current_page?(entries_calendar_path)}"}
            = link_to entries_calendar_path, title: "Calendar View" do
              %i.fa.fa-calendar.hidden-xs
              %span.visible-xs-inline-block CALENDAR

          %li{class: "#{'active' if current_page?(search_path)}"}
            = link_to search_path, title: "Search" do
              %i.fa.fa-search.hidden-xs
              %span.visible-xs-inline-block SEARCH

          - if current_user.is_admin?
            %li.dropdown{class: "#{'active' if params[:controller].in?(['admin', 'inspirations', 'payments'])}"}
              %a.dropdown-toggle{data: { toggle: "dropdown"}, href: "#"}
                %i.fa.fa-lock.hidden-xs
                %span.visible-xs-inline-block ADMIN                
              %ul.dropdown-menu{role: "menu"}
                %li{class: "#{'active' if current_page?(inspirations_path)}"}
                  =link_to inspirations_path, title: "Inspirations" do
                    %i.fa.fa-lightbulb-o
                    &nbsp;Inspirations
                %li{class: "#{'active' if current_page?(payments_path)}"}
                  =link_to payments_path, title: "Payments" do
                    %i.fa.fa-usd
                    &nbsp;Payments              
                %li{class: "#{'active' if current_page?(admin_stats_path)}"}
                  =link_to admin_stats_path, title: "Admin Stats" do
                    %i.fa.fa-bar-chart
                    &nbsp;Stats
                %li{class: "#{'active' if current_page?(admin_photos_path)}"}
                  =link_to admin_photos_path, title: "Admin Photos" do
                    %i.fa.fa-picture-o
                    &nbsp;Photos
                %li{class: "#{'active' if current_page?(admin_users_path)}"}
                  =link_to admin_users_path, title: "Admin Users" do
                    %i.fa.fa-users
                    &nbsp;Users

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          - if current_user.sign_in_count < 10 && !cookies[:viewed_settings] && (current_page?(entries_path) || current_page?(root_path))
            - add_popover = "popover_settings"
            - if current_user.frequency.count > 0
              - current_settings = "You will be emailed at <strong>#{current_user.send_time.strftime("%-I %P")} #{current_user.send_timezone}</strong> on <strong>#{current_user.frequencies}</strong>."
            - else
              - current_settings = "Email reminders are currently <strong>disabled</strong>."
          %li{class: "#{'active' if current_page?(edit_user_registration_path)}", rel: "#{add_popover}", title: "", data: { content: "#{current_settings}", placement: "bottom"}}
            = link_to edit_user_registration_path do
              %span SETTINGS
          %li
            = link_to destroy_user_session_path, method: :delete, title: "Logout" do
              %i.fa.fa-sign-out.hidden-xs
              %span.visible-xs-inline-block LOGOUT

        - else
          %li{class: "#{'active' if params[:controller] == 'registrations'}"}
            = link_to "SIGN UP", new_user_registration_path, class: 'navbar-link'
          %li{class: "#{'active' if params[:controller] == 'devise/sessions'}"}
            = link_to "LOGIN", new_user_session_path, class: 'navbar-link'