config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.is_admin? } do
    resources :inspirations, path: '/admin/inspirations'
    resources :payments, path: '/admin/payments'
    get 'admin/users' => 'admin#users', as: 'admin_users'
    get 'admin/stats' => 'admin#stats', as: 'admin_stats'
    get 'admin/photos' => 'admin#photos', as: 'admin_photos'
  end

  devise_for :users, controllers: { registrations: 'registrations', session: 'sessions', passwords: 'passwords' }

  devise_scope :user do
    get 'settings/(:user_key)'     => 'registrations#settings', as: 'settings'
    match 'unsubscribe/:user_key'  => 'registrations#unsubscribe', as: 'unsubscribe', via: [:put]
  end

  get 'entries/import/(:type)'   => 'import#show', as: 'import'
  match 'entries/import/(:type)' => 'import#update', via: [:put], as: 'import_process'
  match '/entries/import/ohlife/upload'  => 'import#process_ohlife_images', via: [:post], :as => 'import_ohlife_images'
  get 'entries/export'   => 'entries#export', as: 'export_entries'
  get 'entries/calendar' => 'entries#calendar', as: 'entries_calendar'

  get 'past(/:anything)',               to: redirect('/entries')
  get 'entries/random',                 to: 'entries#random', as: 'random_entry'
  get 'entries/:year/:month/:day',      to: 'entries#show',  as: 'day_entry'
  resources :entries, except: [:show]
  get 'entries/(:group)(/:subgroup)',   to: 'entries#index',  as: 'group_entries'  
  get 'latest',                         to: 'entries#latest', as: 'latest_entry'
  get 'review/(:year)',                 to: 'entries#review', as: 'review'
  get 'play',                           to: 'entries#spotify', as: 'spotify'
  get 'search',                         to: 'searches#show'
  get 'write',                          to: redirect('/entries/new')
  get 'privacy',                        to: 'welcome#privacy'
  get 'terms',                          to: 'welcome#terms'
  get 'features',                       to: 'welcome#features'
  get 'faqs',                           to: 'welcome#faqs'
  get 'subscribe',                      to: 'welcome#subscribe'
  get 'donate',                         to: redirect('/subscribe')
  get 'pro',                            to: redirect('/subscribe')
  match 'payment_notify',               to: 'payments#payment_notify', via: [:post]
  get 'ohlife-alternative',             to: 'welcome#ohlife_alternative'
  post 'email_processor',               to: 'griddler/emails#create'
  post 'email_events',                  to: 'email_events#create'

  root 'welcome#index'  

  get "*any", via: :all, to: "errors#not_found"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to latest_entry_path if user_signed_in?
  end
end

app/views/welcome/faqs.html.haml
- title "Dabble Me — Frequently Asked Questions"

.row
  .col-md-2.float-right.hidden-sm.hidden-xs
    .s-faqs-sidebar
      %h4 Contact Us
      %p 
        If your questions are not answered here
        =mail_to("hello@#{ENV['MAIN_DOMAIN']}", "contact us", encode: "hex")
        and we'll be happy to help!
  .col-md-8.col-md-offset-1.well.s-faqs
    .s-entry-date
      %h2.center Frequently Asked Questions
      %h3
        %span PRO FEATURES ONLY
    %div
      - if !signed_in? || current_user.is_free?
        %p
          The following features are only available to users subscribed to
          =link_to("Dabble Me PRO", subscribe_path)+"."
          You can subscribe for $3/month or $30/year.
      %h4 How do I add a photo to my entry?
      %p When you reply to your Dabble Me email, just attach a photo to the email and it'll get saved with your entry. You can also add a photo on the website when you edit an entry. You can add 1 photo per entry, and we support jpeg, gif, png, and heic (iOS 12) formats.

      %h4 How do I edit or delete an entry?
      %p
        When visiting the
        =link_to("entries page", entries_path) + ","
        you'll see an icon that looks like
        &nbsp;
        %i.fa.fa-pencil-square-o
        &nbsp;
        in the top right. Clicking that icon takes you to the edit page. There's a delete button on the right side of the edit page that looks like
        &nbsp;
        %i.fa.fa-trash
        &nbsp;
        in case you'd like to delete your entry.
      
      %h4 Can I write entries on the website?
      %p You can write entries on the website for any date. Simply click "WRITE" at the top.      

      %h4 Can I import from OhLife or any other services?
      %p
        Yes! Simply visit the
        =link_to("Importer", import_path) + "."

    .s-entry-date
      %h3
        %span GENERAL

    %div
      %h4 How do I save a copy of my entries?
      %p          
        You can download a copy of your entries at any time at the bottom of the
        =link_to("settings page", edit_user_registration_path + '#export') + "."
      
      %h4 I'm new and didn't get my scheduled email. How come?
      %p
        Things work differently on your first day. Instead of sending the email at your scheduled time, we send your first email right when you sign up. After your first day though, you'll always get your email according to
        =link_to("your settings", edit_user_registration_path) + "."
      
      %h4 Is there a mobile app?
      %p The site is built using a responsive design, so it will look great and function with ease when viewing it in any mobile browser. Also, the primary action in Dabble Me is writing an entry, which can be done with a phone's email client.
      
      %h4 Are my entries private?
      %p
        We're trying to keep Dabble Me as similar to a real journal as possible, so there's no way to share your entries (no way to email them, no way to post them to Twitter, no way to post them to Facebook, etc.) and they aren't searchable by search engines. Here's a link to our 
        =link_to("privacy policy", privacy_path) + "."
      
      %h4 Can I reply to an email more than once?
      %p Yes - each reply just gets added to that day's entry.

      %h4 What are "Inspirations"
      %p
        Ignore them if you want; they're just little quotes or questions that might inspire you to write. Entries will be tagged with a
        &nbsp;
        %i.fa.fa-lightbulb-o
        &nbsp;
        in the top left of the entry which you can hover over to show the inspiration that inspired the writing for that specific entry.


      %h4 Who created this?
      %p
        This service is created and maintained by
        =link_to("Dabble Dev LLC", "https://paularterburn.com/", target: "_blank") + "."
        The founder of Dabble Dev LLC is Paul Arterburn, who is also the Director of Engineering at
        =link_to "Unreasonable Group", "https://unreasonablegroup.com", target: "_blank"
        helping entrepreneurs bend history in the right direction. Previously, Paul was the technical co-founder of
        =link_to("Brandfolder", "https://brandfolder.com", target: "_blank") + ","
        a digital asset management platform that some of the biggest brands in the world trust with their brand assets.
        %blockquote{style: "display: block; margin-top: 0px;"}
          I created Dabble Me as a way to remember and reflect on my days in a format that would actually trigger me to write — email. If you're curious, I described
          %i why
          and
          %i how
          I built Dabble Me in a blog post:
          =link_to("Increase Your Happiness with Daily Journaling", "https://medium.com/startup-lesson-learned/increase-your-happiness-with-daily-journaling-8109b0700506", target: "_blank") + "."
          %br
          %strong –Paul Arterburn, creator of Dabble Me

      
      %h4 Is this really free?
      %p
        The basic service is, but you're limited to receiving email prompts every other Sunday. If you want premium features like changing email frequency, adding/editing entries from the web, adding photos, rich text entry, calendar view, and search you'll need to
        =link_to "subscribe", subscribe_path
        to Dabble Me PRO.
        %span{style: "display: block; margin-top: 10px;"}
          I've also open-sourced the code on GitHub, so if you're a Ruby on Rails developer and want to contribute head over to the
          = link_to("GitHub repo", "http://github.com/parterburn/dabble.me", title: "View code on GitHub", target: "_blank") + "."

      %h4 If my question wasn't answered here, how can I contact you?
      %p
        Email is best:
        =mail_to("hello@#{ENV['MAIN_DOMAIN']}", "hello@#{ENV['MAIN_DOMAIN']}", encode: "hex")

app/views/welcome/features.html.haml
- title "Dabble Me — Features"

.row
  .col-md-8.col-md-offset-2.s-faqs
    .s-entry-date
      %h2.center Features
      %hr
      %p
        %strong Dabble Me was built in a way to help you actually keep a journal.
      %p It sends you an email every day asking how your day went. Hit reply and start typing anything. You can also include a photo that will remind you of your day. When you're done, hit send, and your entry will be saved instantly.
      %p With every reminder email, we'll include one of your previous entries chosen at random. You might get one from yesterday, last week, or last year.
      %h3
        %span{style: "background-color: #fcfbf9"} PRO FEATURES
    .s-features
      %ul
        %li
          %i.fa.fa-check.s-good
          Change the frequency & days that emails are sent
        %li
          %i.fa.fa-check.s-good
          Attach a photo to your entry from email or web (with support for iOS 12 HEIC format)
        %li
          %i.fa.fa-check.s-good
          Embed Spotify tracks in your entries          
        %li
          %i.fa.fa-check.s-good
          Add new entries via the web
        %li
          %i.fa.fa-check.s-good
          Edit entries
        %li
          %i.fa.fa-check.s-good
          Rich text formatting
        %li
          %i.fa.fa-check.s-good
          Calendar view of all your entries          
        %li
          %i.fa.fa-check.s-good
          Search all of your past entries with support for hashtags
        %li
          %i.fa.fa-check.s-good
          Year in Review
        %li
          %i.fa.fa-check.s-good
          Daily Inspirations for writing ideas
        %li
          %i.fa.fa-check.s-good
          Import from other services          

    .s-entry-date
      %h3
        %span{style: "background-color: #fcfbf9"} FREE LIMITATIONS

    .s-features
      %ul
        %li
          %i.fa.fa-times.s-bad
          Email prompts sent every other Sunday
        %li
          %i.fa.fa-times.s-bad
          No ability to edit or delete entries
        %li
          %i.fa.fa-times.s-bad
          No access to search or calendar
        %li
          %i.fa.fa-times.s-bad
          Simple text entry (i.e. no bold, italics, or lists)

app/views/welcome/index.html.haml
- title "Dabble Me — Your private journal."

.center.s-landing-page
  %h1{title: "Dabble Me"}
    =image_tag("dabble_me_pencil_400.png", alt: "Dabble Me Logo")
  %h2 Your private journal.
  %br
  .col-md-6.col-md-offset-3
    %p
      %span.hidden-xs
        What were you doing last month? How about last week?
        %br
      Dabble Me helps you remember what's happened in your life.
    %br

.clearfix
.center
  = link_to "WRITE YOUR FIRST ENTRY", new_user_registration_path, :class => 'btn btn-info btn-lg col-md-4 col-md-offset-4'
  .clearfix
%br
.clearfix

.col-md-6.col-lg-4.col-lg-offset-2.s-features.top20
  %ul
    %li
      %i.fa.fa-check
      Always private. Never social.
    %li
      %i.fa.fa-check
      Reminders emailed on your schedule
    %li
      %i.fa.fa-check
      Reply-to-post entries
    %li
      %i.fa.fa-check
      Search entries

.col-md-6.col-lg-5.s-features.top20
  %ul
    %li
      %i.fa.fa-check
      Blasts from the past in your inbox
    %li
      %i.fa.fa-check
      Attach an image to save it with the entry
    %li
      %i.fa.fa-check
      Tag your entries with hashtags
    %li
      %i.fa.fa-check
      =link_to "Plus more with Dabble Me PRO", subscribe_path

.row
  .col-md-8.col-md-offset-2{style: "margin-top: 10px;"}
    .email-window
      %h1.titlebar-mail Inbox — Daily Emails
      %nav.controls-mail
        %a.close-mail{:href => "#"} close
        %a.minimize-mail{:href => "#"} minimize
        %a.maximize-mail{:href => "#"} maximize
      .message-window
        .message-header
          .info
            .from-name
              %strong Dabble Me ✏
            .light-text To: your@email.com
            .email-subject{style: "padding: 2px 0;"} It's #{Time.now.yesterday.strftime("%A, %b %-d")}. How was your day?
          .date.hidden-xs
            .light-text= "#{Time.now.yesterday.strftime("%B %-d, %Y")} 8:00pm"
        .message-content{style: "padding: 20px 25px;"}
          %p Reply to this email with your entry for #{Time.now.yesterday.strftime("%B %-d")}.
          %p 
            %strong Remember this? On #{Time.now.yesterday.last_year.strftime("%a, %b %-d, %Y")} (exactly 1 year ago) you wrote...
          %p Had a life changing moment today. Full of love, appreciation, and grateful for what happened today. #Jade become an older sister!
          %p
            %em.small.text-muted Tags: Jade (2 years 3 months)
          %p
            = image_tag "baby.jpg", style: "width: 300px; max-width: 100%;"


.center.hidden-xs
  %h4
    %p Read about Dabble Me in...
    %p
      %strong=link_to "INCREASE YOUR HAPPINESS WITH DAILY JOURNALING", "https://medium.com/startup-lesson-learned/increase-your-happiness-with-daily-journaling-8109b0700506", target: "_blank"
    
.clearfix
%br
%br

app/views/welcome/ohlife_alternative.html.haml
- title "Dabble Me - The free aternative to OhLife"

.center.s-landing-page
  %h1 The Free OhLife Alternative
  %br
  %br
  .clearfix
  =image_tag "ohlifelogo.gif", style: "height:48px;"
  &nbsp;&nbsp;
  %i.fa.fa-arrow-right.muted{style:"font-size:20px;"}
  &nbsp;&nbsp;
  =image_tag("dabble_me_pencil_400.png", alt: "Dabble Me Logo", style: "width:230px;")
  %br
  .col-md-6.col-md-offset-3
    %br
    %h4.muted Replace OhLife with Dabble Me - it was built as a near-replica of OhLife that gives you the same private place to write.
    %br

  = link_to "Import OhLife Entries", new_user_registration_path, :class => 'btn btn-info btn-lg col-md-4 col-md-offset-4'

.col-md-6.col-lg-4.col-lg-offset-2.s-features.top40
  %ul
    %li
      %i.fa.fa-check
      Import OhLife Entries
    %li
      %i.fa.fa-check
      Daily or Weekly Email Reminders
    %li
      %i.fa.fa-check
      Reply-to-post entries
    %li
      %i.fa.fa-check
      Search entries

.col-md-6.col-lg-5.s-features.top40
  %ul
    %li
      %i.fa.fa-check
      \#ThrowbackThursday everyday in your inbox
    %li
      %i.fa.fa-check
      Attach an image to save it with the entry
    %li
      %i.fa.fa-check
      Tag your entries with hashtags      
    %li
      %i.fa.fa-check
      =link_to "Plus more with Dabble Me PRO",subscribe_path

app/views/welcome/privacy.html.haml
- title "Dabble Me — Privacy Policy"

.row
  .col-md-8.col-md-offset-2.well.s-faqs
    %h2.center Privacy Policy
    %hr
    %p
      We take your privacy very seriously. We believe in protecting your information the same way we want ours protected. This Privacy Policy outlines how we treat your information.
      
    %h4 Private Journal
    %p 
      Your journal entries are always private. The only way you can access them is by logging into your account, or by the emails that are sent to your email address only.
      %br
      %br
      There's no way to share your entries. We don't have any integration with Twitter or Facebook, there's no way to make an entry public, and your entries are not searchable by Google. Dabble Me is strictly a private place for you to read and write about how your days went.
      
    %h4 Information Collected
    %p
      Dabble Me only collects information it needs so that you can use the service. Your information is never shared or sold to any third parties.
      
    %h4 Test Run
    %p
      If you're unhappy with the service for any reason, you can delete your account in your account settings. This permanently deletes your account and all of your entries.
      
    %h4 Privacy Policy Changes
    %p
      Though most changes will probably be minor, Dabble Me may make changes to its Privacy Policy. If so, the new Privacy Policy will be posted on this page.
      
    %h4 Questions?
    %p
      Please send us an email at&nbsp;
      %span>=mail_to "hello@#{ENV['MAIN_DOMAIN']}", "hello@#{ENV['MAIN_DOMAIN']}", :encode=>"hex"
      \. We're happy to help out and answer any of your questions.

app/views/welcome/subscribe.html.haml
- title "Dabble Me — Pricing"

.row
  %br
  .col-md-8.col-md-offset-2
    - unless current_user&.is_pro?
      %h4.text-muted Dabble Me is free with limitations.
      %p.text-muted Email prompts are only sent every other Sunday.
      %hr
      %h3{style: "color: #a41100"} Dabble Me PRO is just $3 per month.
      %p.s-features
        %strong Subscribing will unlock all premium features on your account. Choose a plan below:

    .center
      - if user_signed_in?
        - if current_user.is_pro?
          .col-md-12.alert.alert-info{style: "text-align:center;"}
            Currently subscribed to:
            %strong #{current_user.plan_details.html_safe}
            - if current_user.plan_type.present?
              %span{style: "font-size:12px;display:block;margin-top:10px;"} Modify or cancel your subscription at #{current_user.plan_type.html_safe}.
            - else
              %span{style: "font-size:12px;display:block;margin-top:10px;"} Your PRO account is being provided free of charge.

        - elsif params[:paypal] === 'true'
          %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
            %input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}
            %input{:name => "item_name", :type => "hidden", :value => "Dabble Me PRO for #{current_user.user_key}"}
            %input{:name => "first_name", :type => "hidden", :value => "#{current_user.first_name}"}
            %input{:name => "last_name", :type => "hidden", :value => "#{current_user.last_name}"}
            %input{:name => "email", :type => "hidden", :value => "#{current_user.email}"}
            %input{:name => "night_phone_a", :type => "hidden", :value => "555"}
            %input{:name => "night_phone_b", :type => "hidden", :value => "555"}
            %input{:name => "night_phone_c", :type => "hidden", :value => "5555"}
            %input{:name => "dabble_me_email", :type => "hidden", :value => "#{current_user.email}"}
            %input{:name => "hosted_button_id", :type => "hidden", :value => "#{ENV['PAYPAL_HOSTED_BUTTON_ID']}"}
            %input{:alt => "PayPal - The safer, easier way to pay online!", :border => "0", :name => "submit", :src => "https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif", :type => "image"}
            %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/en_US/i/scr/pixel.gif", :width => "1"}

        - elsif params[:gumroad] === 'true'
          .col-md-12.alert.alert-success{style: "text-align:center;"}
            %script{:src => "https://gumroad.com/js/gumroad.js", :type => "text/javascript"}
            %h4
              Subscribe now using any major credit card.
            %p{style: "margin-top:20px;"}
              %a.gumroad-button{:href => "https://gumroad.com/l/dabbleme?email=#{current_user.email}"} Subscribe Now & Activate PRO Features

        - else
          %div{style: "text-align:center;"}
            %script{:src => "https://app.payhere.co/embed/embed.js", :type => "text/javascript"}
            = render "payments/payhere"
            .row
              .col-sm-7{style: "margin: 5px auto 0;"}
                %button.btn.btn-success.btn-block.btn-lg{:"style" => "height: 55px;", :"onclick" => "payhere('yearly');" }
                  $30
                  %span{style: "font-size: 13px; color: #ddd"}<> ／
                  year
                  %br
                  %span{style: "font-size: 12px;margin-top: -2px; display: block;color: #307530;"} 2 months free
              .col-sm-5{style: "margin: 5px auto;"}
                %button.btn.btn-success.btn-block.btn-lg{:"style" => "height: 55px;", :"onclick" => "payhere('monthly');" }
                  $3
                  %span{style: "font-size: 13px; color: #ddd"}<> ／
                  month
            .clearfix

      - else
        - session["user_return_to"] = subscribe_path
        .col-md-12.alert.alert-info{style: "text-align:center;"}
          .row
            .col-xs-6
              =link_to "Sign Up for PRO", new_user_registration_path, class: "btn btn-primary btn-block"
            .col-xs-6
              =link_to "Login to Subscribe", new_user_session_path, class: "btn btn-primary btn-block"

    .s-features
      %ul
        %li
          %i.fa.fa-check
          Change the frequency & days that emails are sent
        %li
          %i.fa.fa-check
          Attach a photo to your entry (email or web)
        %li
          %i.fa.fa-check
          Import entries from other services
        %li
          %i.fa.fa-check
          Embed Spotify tracks in your entries
        %li
          %i.fa.fa-check
          Add new entries via the web
        %li
          %i.fa.fa-check
          Edit entries
        %li
          %i.fa.fa-check
          Rich text formatting
        %li
          %i.fa.fa-check
          Calendar view of all your entries
        %li
          %i.fa.fa-check
          Search all of your past entries with support for hashtags
        %li
          %i.fa.fa-check
          Year in Review
%br