config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.is_admin? } do
    resources :inspirations, path: '/admin/inspirations'
    resources :payments, path: '/admin/payments'
    get 'admin/users' => 'admin#users', as: 'admin_users'
    get 'admin/stats' => 'admin#stats', as: 'admin_stats'
    get 'admin/photos' => 'admin#photos', as: 'admin_photos'
  end

  devise_for :users, controllers: { registrations: 'registrations', session: 'sessions', passwords: 'passwords' }

  devise_scope :user do
    get 'settings/(:user_key)'     => 'registrations#settings', as: 'settings'
    match 'unsubscribe/:user_key'  => 'registrations#unsubscribe', as: 'unsubscribe', via: [:put]
  end

  get 'entries/import/(:type)'   => 'import#show', as: 'import'
  match 'entries/import/(:type)' => 'import#update', via: [:put], as: 'import_process'
  match '/entries/import/ohlife/upload'  => 'import#process_ohlife_images', via: [:post], :as => 'import_ohlife_images'
  get 'entries/export'   => 'entries#export', as: 'export_entries'
  get 'entries/calendar' => 'entries#calendar', as: 'entries_calendar'

  get 'past(/:anything)',               to: redirect('/entries')
  get 'entries/random',                 to: 'entries#random', as: 'random_entry'
  get 'entries/:year/:month/:day',      to: 'entries#show',  as: 'day_entry'
  resources :entries, except: [:show]
  get 'entries/(:group)(/:subgroup)',   to: 'entries#index',  as: 'group_entries'  
  get 'latest',                         to: 'entries#latest', as: 'latest_entry'
  get 'review/(:year)',                 to: 'entries#review', as: 'review'
  get 'play',                           to: 'entries#spotify', as: 'spotify'
  get 'search',                         to: 'searches#show'
  get 'write',                          to: redirect('/entries/new')
  get 'privacy',                        to: 'welcome#privacy'
  get 'terms',                          to: 'welcome#terms'
  get 'features',                       to: 'welcome#features'
  get 'faqs',                           to: 'welcome#faqs'
  get 'subscribe',                      to: 'welcome#subscribe'
  get 'donate',                         to: redirect('/subscribe')
  get 'pro',                            to: redirect('/subscribe')
  match 'payment_notify',               to: 'payments#payment_notify', via: [:post]
  get 'ohlife-alternative',             to: 'welcome#ohlife_alternative'
  post 'email_processor',               to: 'griddler/emails#create'
  post 'email_events',                  to: 'email_events#create'

  root 'welcome#index'  

  get "*any", via: :all, to: "errors#not_found"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user, optional: true
  validates :date, presence: true, valid_date: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!

  skip_before_action :authenticate_user!, only: [:payment_notify]
  skip_before_action :authenticate_admin!, only: [:payment_notify]
  skip_before_action :verify_authenticity_token, only: [:payment_notify]

  def index
    @monthlys = User.pro_only.monthly
    @yearlys =  User.pro_only.yearly

    @monthly_recurring = 0
    @monthlys.each do |user|
      @monthly_recurring += user.payments.last.amount
    end

    @annual_recurring = 0
    @yearlys.each do |user|
      @annual_recurring += user.payments.last.amount
    end

    @mrr = @monthly_recurring.to_i + (@annual_recurring.to_i/12)

    @payments = Payment.includes(:user).all.order("date DESC, id DESC")
    params[:per] ||= 100
    @paginated_payments = Kaminari.paginate_array(@payments).page(params[:page]).per(params[:per])
  end

  def new
    @payment = Payment.new
  end

  def create

    if params[:user_email].present?
      user = User.find_by(email: params[:user_email].downcase)
      params[:payment][:user_id] = user.id if user.present?
    end

    @payment = Payment.create(payment_params)

    if @payment.save
      if user.present? && params["send_thanks"] == 1
        UserMailer.thanks_for_paying(user).deliver_later
        flash[:notice] = "Payment added successfully & thanks was sent!"
      else
        flash[:notice] = "Payment added successfully!"
      end
      user.update(user_params) if user.present? && user_params[:plan].present?
      redirect_to payments_path
    else
      render 'new'
    end
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])
    if params[:user_email].present?
      user = User.find_by(email: params[:user_email].downcase)
      params[:payment][:user_id] = user.id if user.present?
    end

    if @payment.update(payment_params)
      user.update(user_params) if user.present? && user_params[:plan].present?
      flash[:notice] = "Payment successfully updated!"
      redirect_to payments_path
    else
      render 'edit'
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = 'Payment deleted successfully.'
    redirect_to payments_path
  end

  def payment_notify
    if payhere? && valid_payhere_signature?
      processed_params = process_payhere
    elsif gumroad?
      processed_params = process_gumroad
    elsif paypal?
      processed_params = process_paypal
    else
      Rails.logger.warn("Payment notification not processed: #{params}")
    end

    @user.update(processed_params) if @user.present?
    head :ok, content_type: 'text/html'
  end

  private

  def gumroad?
    params[:email].present? &&
      params[:seller_id] == ENV['GUMROAD_SELLER_ID'] &&
      params[:product_id] == ENV['GUMROAD_PRODUCT_ID']
  end

  def paypal?
    params[:item_name].present? &&
      params[:item_name].include?('Dabble Me') &&
      params[:payment_status].present? &&
      params[:payment_status] == "Completed" &&
      params[:receiver_id] == ENV['PAYPAL_SELLER_ID']
  end

  def payhere?
    params[:customer].present? &&
      (params[:membership_plan].present? && params[:membership_plan][:name].include?("Dabble Me"))
  end

  def process_payhere
    if params[:event] == "payment.failed"
      Rails.logger.warn("Failed payment of $#{params[:payment][:amount]} for #{params[:customer][:email]}")
    else
      @user = User.find_by(payhere_id: params[:customer][:id])
      @user = User.find_by(email: params[:customer][:email].downcase) if @user.blank?
      paid = params[:membership_plan][:price]
      frequency = params[:membership_plan][:billing_interval] == "month" ? "Monthly" : "Yearly"

      if @user.present? && @user.payments.count > 0 && Payment.where(user_id: @user.id).last.date.to_date === Time.now.to_date
        # duplicate, don't send
      elsif @user.present?
        Payment.create(user_id: @user.id, comments: "PayHere #{frequency} from #{params[:customer][:email]}", date: "#{Time.now.strftime("%Y-%m-%d")}", amount: paid )
        begin
          UserMailer.thanks_for_paying(@user).deliver_later if @user.payments.count == 1
        rescue StandardError => e
          Rails.logger.warn("Error sending PayHere thanks_for_paying email email to #{@user.email}: #{e}")
        end
      end

      begin
        UserMailer.no_user_here(params[:customer][:email], 'PayHere', params[:customer][:id]).deliver_later if @user.blank?
      rescue StandardError => e
        Rails.logger.warn("Error sending no_user_her email to #{params[:customer][:email]}: #{e}")
      end

      { plan: "PRO #{frequency} PayHere", payhere_id:  params[:customer][:id] }
    end
  end

  def process_gumroad
    @user = User.find_by(gumroad_id: params[:purchaser_id])
    @user = User.find_by(email: params[:email].downcase) if @user.blank?
    paid = params[:price].to_f / 100
    if params[:recurrence].present?
      frequency = params[:recurrence].titleize
    else
      frequency = paid.to_i > 10 ? 'Yearly' : 'Monthly'
    end
    if @user.present? && @user.payments.count > 0 && Payment.where(user_id: @user.id).last.date.to_date === Time.now.to_date
      # duplicate, don't send
    elsif @user.present?
      Payment.create(user_id: @user.id, comments: "Gumroad #{frequency} from #{params[:email]}", date: "#{Time.now.strftime("%Y-%m-%d")}", amount: paid )
      begin
        UserMailer.thanks_for_paying(@user).deliver_later if @user.payments.count == 1
      rescue StandardError => e
        Rails.logger.warn("Error sending Gumroad thanks_for_paying email email to #{@user.email}: #{e}")
      end
    end

    begin
      UserMailer.no_user_here(params[:email], 'Gumroad', params[:purchaser_id]).deliver_later if @user.blank?
    rescue StandardError => e
      Rails.logger.warn("Error sending no_user_here email to #{params[:email]}: #{e}")
    end

    { plan: "PRO #{frequency} Gumroad", gumroad_id:  params[:purchaser_id] }
  end

  def process_paypal
    user_key = params[:item_name].gsub('Dabble Me PRO for ','') if params[:item_name].present?
    @user = User.find_by(user_key: user_key)

    paid = params[:mc_gross]
    frequency = paid.to_i > 10 ? 'Yearly' : 'Monthly'

    if @user.present? && @user.payments.count > 0 && Payment.where(user_id: @user.id).last.date.to_date === Time.now.to_date
      # duplicate webhook, don't save
    elsif @user.present?
      Payment.create(user_id: @user.id, comments: "Paypal #{frequency} from #{params[:payer_email]}", date: "#{Time.now.strftime("%Y-%m-%d")}", amount: paid )
      begin
        UserMailer.thanks_for_paying(@user).deliver_later if @user.payments.count == 1
      rescue StandardError => e
        Rails.logger.warn("Error sending Paypal thanks_for_paying email to #{@user.email}: #{e}")
      end
    end

    UserMailer.no_user_here(params[:payer_email], 'PayPal', nil).deliver_later if @user.blank?
    { plan: "PRO #{frequency} PayPal", gumroad_id:  @user&.gumroad_id}
  end

  def payment_params
    params.require(:payment).permit(:amount, :date, :user_id,  :comments)
  end

  def user_params
    params.permit(:plan, :gumroad_id, :payhere_id)
  end

  def valid_payhere_signature?
    return true if Rails.env.test?
    digest = OpenSSL::Digest.new("sha1")
    expected = OpenSSL::HMAC.hexdigest(digest, ENV["PAYHERE_SHARED_SECRET"].to_s, request.raw_post)

    Rack::Utils.secure_compare(expected, request.headers["HTTP_X_SIGNATURE"])
  end
end

app/views/payments/_payhere.html.haml
:javascript
  function payhere(plan) {
    PayHere.launch({
      embedURL: "https://app.payhere.co/dabble-me/dabble-me-pro-" + plan,
      disableCustomer: "yes",
      customerName: "#{raw(current_user.full_name&.escape_javascript)}",
      customerEmail: "#{current_user.email}",
      customFields: {
        dabble_id: "#{current_user.id}"
      },
      onSuccess: function(payment) {
        setTimeout(function() { location.reload(); }, 2000);
      }
    });
  }

app/views/payments/edit.html.haml
- title "Edit Payment on Dabble Me"

.row
  %br
  .col-md-8.col-md-offset-2.well

    = form_for :payment, url: payment_path(@payment), method: :patch do |f|

      -if @payment.errors.any?
        #error_explanation
          .alert.alert-danger
            - @payment.errors.full_messages.each do |msg|
              %p= msg

      %div
        = f.label :date
        .input-group.date
          %span.input-group-addon
            %i.fa.fa-calendar
          = f.text_field :date, :value =>  @payment.date.strftime("%B %-d, %Y"), :placeholder=>"2014-10-31", :class => "form-control pickadate"
        %br

      %div
        = f.label :amount
        = f.text_field :amount, :class => "form-control"
        %br

      %div
        = f.label :user_id
        = f.text_field :user_id, :class => "form-control"
        %br

      %div
        = label_tag :user_email
        = text_field_tag :user_email, "#{@payment.user.email if @payment.user}", :class => "form-control"
        %br

      %div
        = label_tag :plan
        = text_field_tag :plan, "#{@payment.user.plan if @payment.user}", :class => "form-control"
        %br

      %div
        = label_tag :gumroad_id
        = text_field_tag :gumroad_id, "#{@payment.user.gumroad_id if @payment.user}", :class => "form-control"
        %br

      %div
        = label_tag :payhere_id
        = text_field_tag :payhere_id, "#{@payment.user.payhere_id if @payment.user}", :class => "form-control"
        %br        

      %div
        = f.label :comments
        = f.text_area :comments, :class => "form-control", :rows => 2
        %br

      %div
        = f.submit "Edit Payment", :class => "form-control btn btn-primary"

:javascript
  var tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  $.extend($.fn.pickadate.defaults, {
    format: 'mmmm d, yyyy',
    selectYears: true,
    selectMonths: true,
    max: tomorrow
  })

  $('.pickadate').pickadate();    

app/views/payments/index.html.haml
- title "Payments on Dabble Me"

.row
  .col-md-2
    %p
      =link_to "Add new payment", new_payment_path, class: "btn btn-info"
  .col-md-5
    %p
      %strong
        Total Payments:
        =@payments.length
        for
        =number_to_currency(@payments.sum(:amount))
    %p
      %strong
        MRR:
        =number_to_currency(@mrr)        
  .col-md-5
    %p
      %strong
        Monthly Subs:
        =@monthlys.count
        for
        =number_to_currency(@monthly_recurring.to_i)
        per month
    %p
      %strong
        Annual Subs:
        =@yearlys.count
        for
        =number_to_currency(@annual_recurring.to_i)      
        per year  

.row
  .col-md-1
    %h4 Actions
  .col-md-2
    %h4 Date
  .col-md-1
    %h4 Amount
  .col-md-3
    %h4 User
  .col-md-2
    %h4 Plan    
  .col-md-3
    %h4 Comments

- @paginated_payments.each do |payment|
  .row.s-inspiration-admin
    .col-md-1
      =link_to edit_payment_path(payment), :class=>"noline", title: "Edit Payment" do
        %i.fa.fa-pencil
      &nbsp;
      = link_to payment_path(payment), title: "Delete Payment", class: "s-delete", method: :delete, data: { confirm: 'Are you sure you want to delete this payment? There is no undo.' } do
        %i.fa.fa-trash
    .col-md-2
      =payment.date.strftime("%Y-%m-%d")
    .col-md-1
      =number_to_currency(number_with_delimiter(payment.amount))
    .col-md-3
      - if payment.user
        =payment.user.email
      - else
        =payment.user_id
    .col-md-2
      - if payment.user
        =payment.user.plan      
    .col-md-3
      =payment.comments

.row
  .col-md-12
    .center
      = paginate @paginated_payments

app/views/payments/new.html.haml
- title "New Payment on Dabble Me"

.row
  %br
  .col-md-8.col-md-offset-2.well

    = form_for :payment, url: payments_path do |f|

      -if @payment.errors.any?
        #error_explanation
          .alert.alert-danger
            - @payment.errors.full_messages.each do |msg|
              %p= msg

      %div
        = f.label :date
        .input-group.date
          %span.input-group-addon
            %i.fa.fa-calendar
          = f.text_field :date, :value =>  "#{@payment.date.present? ? @payment.date.strftime("%m %-d, %Y") : Date.today.strftime("%B %-d, %Y")}", :placeholder=>"2014-10-31", :class => "form-control pickadate"
        %br

      %div
        = f.label :amount
        = f.text_field :amount, :class => "form-control"
        %br

      %div
        = f.label :user_id
        = f.text_field :user_id, :class => "form-control"
        %br

      %div
        = label_tag :user_email
        = text_field_tag :user_email, "#{@payment.user.email if @payment.user}", :class => "form-control"
        %br

      %div
        = label_tag :plan
        = text_field_tag :plan, "#{@payment.user.plan if @payment.user}", :class => "form-control"
        %br

      %div
        = label_tag :gumroad_id
        = text_field_tag :gumroad_id, "#{@payment.user.gumroad_id if @payment.user}", :class => "form-control"
        %br

      %div
        = label_tag :payhere_id
        = text_field_tag :payhere_id, "#{@payment.user.payhere_id if @payment.user}", :class => "form-control"
        %br        

      %div
        = f.label :send_thanks, "Send thanks: "
        = f.check_box :send_thanks, :checked => true
        %br
        %br

      %div
        = f.label :comments
        = f.text_area :comments, :class => "form-control", :rows => 2
        %br

      %div
        = f.submit "Add Payment", :class => "form-control btn btn-primary"

-if @payment.date.blank?
  :javascript
    var tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    $.extend($.fn.pickadate.defaults, {
      format: 'mmmm d, yyyy',
      selectYears: true,
      selectMonths: true,
      max: tomorrow
    })

    $('.pickadate').pickadate();